# Cloud Build configuration for Event Ticketing Platform
# Triggered on push to main branch
#
# Workflow:
# 1. Build all Docker images in parallel
# 2. Push images to Artifact Registry
# 3. Deploy all services to Cloud Run
#
# Note: Tests are skipped for MVP to speed up deployment.
# TODO: Add automated tests back after stabilizing test environment.

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1800s  # 30 minutes

substitutions:
  _PROJECT_ID: 'project-4aa96947-a91f-4413-a51'
  _REGION: 'asia-southeast2'
  _ARTIFACT_REGISTRY: 'asia-southeast2-docker.pkg.dev/project-4aa96947-a91f-4413-a51/event-ticketing'

steps:
  # ============================================
  # STEP 1: Build Docker Images (Parallel)
  # ============================================

  # Auth Service
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-auth-service'
    args:
      - 'build'
      - '-t'
      - '${_ARTIFACT_REGISTRY}/auth-service:$COMMIT_SHA'
      - '-t'
      - '${_ARTIFACT_REGISTRY}/auth-service:latest'
      - '-f'
      - 'backend/services/auth-service/Dockerfile'
      - 'backend'
    waitFor: ['-']

  # Gateway Service
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-gateway-service'
    args:
      - 'build'
      - '-t'
      - '${_ARTIFACT_REGISTRY}/gateway-service:$COMMIT_SHA'
      - '-t'
      - '${_ARTIFACT_REGISTRY}/gateway-service:latest'
      - '-f'
      - 'backend/services/gateway-service/Dockerfile'
      - 'backend'
    waitFor: ['-']

  # Event Service
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-event-service'
    args:
      - 'build'
      - '-t'
      - '${_ARTIFACT_REGISTRY}/event-service:$COMMIT_SHA'
      - '-t'
      - '${_ARTIFACT_REGISTRY}/event-service:latest'
      - '-f'
      - 'backend/services/event-service/Dockerfile'
      - 'backend'
    waitFor: ['-']

  # Ticketing Service
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-ticketing-service'
    args:
      - 'build'
      - '-t'
      - '${_ARTIFACT_REGISTRY}/ticketing-service:$COMMIT_SHA'
      - '-t'
      - '${_ARTIFACT_REGISTRY}/ticketing-service:latest'
      - '-f'
      - 'backend/services/ticketing-service/Dockerfile'
      - 'backend'
    waitFor: ['-']

  # Payment Service
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-payment-service'
    args:
      - 'build'
      - '-t'
      - '${_ARTIFACT_REGISTRY}/payment-service:$COMMIT_SHA'
      - '-t'
      - '${_ARTIFACT_REGISTRY}/payment-service:latest'
      - '-f'
      - 'backend/services/payment-service/Dockerfile'
      - 'backend'
    waitFor: ['-']

  # Notification Service
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-notification-service'
    args:
      - 'build'
      - '-t'
      - '${_ARTIFACT_REGISTRY}/notification-service:$COMMIT_SHA'
      - '-t'
      - '${_ARTIFACT_REGISTRY}/notification-service:latest'
      - '-f'
      - 'backend/services/notification-service/Dockerfile'
      - 'backend'
    waitFor: ['-']

  # ============================================
  # STEP 3: Push Images to Artifact Registry (Parallel)
  # ============================================

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-auth-service'
    args:
      - 'push'
      - '--all-tags'
      - '${_ARTIFACT_REGISTRY}/auth-service'
    waitFor: ['build-auth-service']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-gateway-service'
    args:
      - 'push'
      - '--all-tags'
      - '${_ARTIFACT_REGISTRY}/gateway-service'
    waitFor: ['build-gateway-service']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-event-service'
    args:
      - 'push'
      - '--all-tags'
      - '${_ARTIFACT_REGISTRY}/event-service'
    waitFor: ['build-event-service']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-ticketing-service'
    args:
      - 'push'
      - '--all-tags'
      - '${_ARTIFACT_REGISTRY}/ticketing-service'
    waitFor: ['build-ticketing-service']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-payment-service'
    args:
      - 'push'
      - '--all-tags'
      - '${_ARTIFACT_REGISTRY}/payment-service'
    waitFor: ['build-payment-service']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-notification-service'
    args:
      - 'push'
      - '--all-tags'
      - '${_ARTIFACT_REGISTRY}/notification-service'
    waitFor: ['build-notification-service']

  # ============================================
  # STEP 4: Deploy to Cloud Run (Parallel)
  # ============================================

  # Deploy Auth Service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-auth-service'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'auth-service'
      - '--image=${_ARTIFACT_REGISTRY}/auth-service:$COMMIT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
    waitFor: ['push-auth-service']

  # Deploy Gateway Service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-gateway-service'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'gateway-service'
      - '--image=${_ARTIFACT_REGISTRY}/gateway-service:$COMMIT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=CORS_ALLOWED_ORIGINS=http://localhost:3000,https://localhost:3000'
    waitFor: ['push-gateway-service']

  # Deploy Event Service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-event-service'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'event-service'
      - '--image=${_ARTIFACT_REGISTRY}/event-service:$COMMIT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
    waitFor: ['push-event-service']

  # Deploy Ticketing Service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-ticketing-service'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'ticketing-service'
      - '--image=${_ARTIFACT_REGISTRY}/ticketing-service:$COMMIT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
    waitFor: ['push-ticketing-service']

  # Deploy Payment Service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-payment-service'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'payment-service'
      - '--image=${_ARTIFACT_REGISTRY}/payment-service:$COMMIT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
    waitFor: ['push-payment-service']

  # Deploy Notification Service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-notification-service'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'notification-service'
      - '--image=${_ARTIFACT_REGISTRY}/notification-service:$COMMIT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
    waitFor: ['push-notification-service']

  # ============================================
  # STEP 5: Deployment Summary
  # ============================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deployment-summary'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "========================================" && \
        echo "🎉 Deployment Complete!" && \
        echo "========================================" && \
        echo "Commit: $COMMIT_SHA" && \
        echo "Branch: $BRANCH_NAME" && \
        echo "" && \
        echo "Services deployed:" && \
        echo "  ✅ auth-service" && \
        echo "  ✅ gateway-service" && \
        echo "  ✅ event-service" && \
        echo "  ✅ ticketing-service" && \
        echo "  ✅ payment-service" && \
        echo "  ✅ notification-service" && \
        echo "========================================" && \
        echo "Gateway URL: https://gateway-service-kyficgrsia-et.a.run.app" && \
        echo "========================================"
    waitFor:
      - 'deploy-auth-service'
      - 'deploy-gateway-service'
      - 'deploy-event-service'
      - 'deploy-ticketing-service'
      - 'deploy-payment-service'
      - 'deploy-notification-service'

# Images to be pushed to Artifact Registry
images:
  - '${_ARTIFACT_REGISTRY}/auth-service:$COMMIT_SHA'
  - '${_ARTIFACT_REGISTRY}/auth-service:latest'
  - '${_ARTIFACT_REGISTRY}/gateway-service:$COMMIT_SHA'
  - '${_ARTIFACT_REGISTRY}/gateway-service:latest'
  - '${_ARTIFACT_REGISTRY}/event-service:$COMMIT_SHA'
  - '${_ARTIFACT_REGISTRY}/event-service:latest'
  - '${_ARTIFACT_REGISTRY}/ticketing-service:$COMMIT_SHA'
  - '${_ARTIFACT_REGISTRY}/ticketing-service:latest'
  - '${_ARTIFACT_REGISTRY}/payment-service:$COMMIT_SHA'
  - '${_ARTIFACT_REGISTRY}/payment-service:latest'
  - '${_ARTIFACT_REGISTRY}/notification-service:$COMMIT_SHA'
  - '${_ARTIFACT_REGISTRY}/notification-service:latest'
