// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.2
// source: ticketing/ticketing.proto

package ticketing

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TicketingServiceClient is the client API for TicketingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TicketingServiceClient interface {
	// ConfirmPayment confirms payment and generates tickets
	ConfirmPayment(ctx context.Context, in *ConfirmPaymentRequest, opts ...grpc.CallOption) (*ConfirmPaymentResponse, error)
}

type ticketingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTicketingServiceClient(cc grpc.ClientConnInterface) TicketingServiceClient {
	return &ticketingServiceClient{cc}
}

func (c *ticketingServiceClient) ConfirmPayment(ctx context.Context, in *ConfirmPaymentRequest, opts ...grpc.CallOption) (*ConfirmPaymentResponse, error) {
	out := new(ConfirmPaymentResponse)
	err := c.cc.Invoke(ctx, "/ticketing.TicketingService/ConfirmPayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TicketingServiceServer is the server API for TicketingService service.
// All implementations must embed UnimplementedTicketingServiceServer
// for forward compatibility
type TicketingServiceServer interface {
	// ConfirmPayment confirms payment and generates tickets
	ConfirmPayment(context.Context, *ConfirmPaymentRequest) (*ConfirmPaymentResponse, error)
	mustEmbedUnimplementedTicketingServiceServer()
}

// UnimplementedTicketingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTicketingServiceServer struct {
}

func (UnimplementedTicketingServiceServer) ConfirmPayment(context.Context, *ConfirmPaymentRequest) (*ConfirmPaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmPayment not implemented")
}
func (UnimplementedTicketingServiceServer) mustEmbedUnimplementedTicketingServiceServer() {}

// UnsafeTicketingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TicketingServiceServer will
// result in compilation errors.
type UnsafeTicketingServiceServer interface {
	mustEmbedUnimplementedTicketingServiceServer()
}

func RegisterTicketingServiceServer(s grpc.ServiceRegistrar, srv TicketingServiceServer) {
	s.RegisterService(&TicketingService_ServiceDesc, srv)
}

func _TicketingService_ConfirmPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketingServiceServer).ConfirmPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ticketing.TicketingService/ConfirmPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketingServiceServer).ConfirmPayment(ctx, req.(*ConfirmPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TicketingService_ServiceDesc is the grpc.ServiceDesc for TicketingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TicketingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ticketing.TicketingService",
	HandlerType: (*TicketingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConfirmPayment",
			Handler:    _TicketingService_ConfirmPayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ticketing/ticketing.proto",
}
